=== NephtysOrg/smcw/livrable3/bd__randonnee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auteur : Charles Follet -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="randonnee">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="etape"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--  une étape doit impérativement contenir les balises entre () -->
  <xs:element name="etape">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="distance"/>
        <xs:element ref="temps"/>
        <xs:element ref="description"/>
        <xs:element minOccurs="0" ref="lieux"/>
        <!-- Une étape peut ne pas avoir de lieu remarquable -->
      </xs:sequence>
      <xs:attributeGroup ref="attlist.etape"/>
    </xs:complexType>

  </xs:element>
  <xs:attributeGroup name="attlist.etape">
    <xs:attribute name="numero" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="1"/>
          <xs:maxInclusive value="20"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="libelle" use="required" type="xs:string"/>
  </xs:attributeGroup>
  <xs:element name="distance">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.distance"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.distance">
    <xs:attribute name="valeur" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minExclusive value="0"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="unite" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="m"/>
          <xs:enumeration value="km"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="temps">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.temps"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.temps">
    <xs:attribute name="heure" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="72"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="minute" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="59"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="lieux">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="lieu"/>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="UniqueAddKey">
      <xs:selector xpath="lieu"/>
      <xs:field xpath="."/>
    </xs:unique>
  </xs:element>
  <xs:element name="lieu">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute ref="type" use="required"/>
          <xs:attribute ref="coord" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>

  </xs:element>
  <xs:attribute name="type">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="voie_routiere"/>
        <xs:enumeration value="voie_fluviale"/>
        <xs:enumeration value="lieu_dit"/>
        <xs:enumeration value="batiment"/>
        <xs:enumeration value="ville"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="coord">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="(\-?\d+(\.\d+)?),\s*(\-?\d+(\.\d+)?)"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

</xs:schema>

=== NephtysOrg/smcw/livrable3/bd__randonnee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auteur : Charles Follet -->

<randonnee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="bd__randonnee.xsd">
    <etape numero="1" libelle="Avenue Joliot-Curie">
        <distance valeur="1220" unite="m"/>
        <temps heure="00" minute="15"/>
        <description>
            Il faut tourner le dos au gave de Pau et prendre la rue de l'Artisanat vers le sud. Traversez la double-voie et poursuivez en face par l'avenue Joliot-Curie. Laissez à droite le lycée professionnel de Jurançon tout en métal brillant et en tubes métalliques puis franchissez une passerelle pour pénétrer dans une zone de pavillons modernes. Poursuivez par la rue Auguste Renoir puis, au bout, virer à droite en direction de la rocade. 
        </description>
        <lieux>
            <lieu type="voie_fluviale" coord="43.287530, -0.391115">gave de Pau</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">rue de l'Artisanat</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">avenue Joliot-Curie</lieu>
            <lieu type="batiment" coord="43.287530, -0.391115">lycée professionnel de Jurançon</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">rue Auguste Renoir</lieu>
        </lieux>
    </etape>
    
    <etape numero="2" libelle="Le Clos Touzet">
        <distance valeur="2300" unite="m"/>
        <temps heure="00" minute="45"/>
        <description>
            Traverser la rocade puis continuez en vous élevant par le chemin de Monplaisir, à la limite d'un bois. Laisser les bâtiments du « Nid béarnais » à gauche et continuer en sous-bois. Débouchez au sommet du coteau face « Au Clos Touzet » où la vue sur la plaine de Pau mérite un long coup d'oeil. Poursuivez en face. Ne pas descendre trop longtemps vers Jurançon, mais suivre l'avenue des Frères Barthélemy en face.
        </description>
        <lieux>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">chemin de Monplaisir</lieu>
            <lieu type="batiment" coord="43.287530, -0.391115">bâtiments du « Nid béarnais »</lieu>
            <lieu type="lieu_dit" coord="43.287530, -0.391115">Clos Touzet</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">avenue des Frères Barthélemy</lieu>
        </lieux>
    </etape>
    
    <etape numero ="3" libelle="Le chemin Mirabel">
        <distance valeur="1200" unite="m"/>  
        <temps heure="00" minute="20"/> 
        <description>
            Face à l'entrée du Clos Henri IV, au N 223, descendre à droite le chemin Mirabel (panneau) qui se faufile en sous-bois. Juste avant l'entrée de la ferme Larrau (remarquer le séquoia isolé) prenez un chemin creux à gauche qui plonge dans un sous-bois magnifique. Il décrit une épingle et s'enfonce dans une forêt où la lumière pénètre difficilement. Rejoignez le lit d'un petit ruisseau que vous suivez vers l'aval. Mousses, lichens, fougères constituent le décor luxuriant de cette descente humide.
        </description>
        <lieux>
            <lieu type="lieu_dit" coord="43.287530, -0.391115">Clos Henri IV</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">chemin Mirabel</lieu>
            <lieu type="batiment" coord="43.287530, -0.391115">ferme Larrau</lieu>
        </lieux>
    </etape>
    
    <etape numero ="4" libelle="Le Clos Lapeyre">
        <distance valeur="2430" unite="m"/>  
        <temps heure="00" minute="45"/> 
        <description>
            Emprunter la route à gauche (chemin Vignau) où vous rencontrez un chemin équestre (itinéraire équestre Pyrénéen) que vous suivrez maintenant facilement vers le sud. Franchissez un pont et grimpez une piste cimentée « camin de Sobolle ». Dépasser la belle ferme Sobolle et continuer dans le bois. Rejoignez un chemin goudronné et le suivre à gauche vers le Clos Lapeyre. Après la première vigne, descendre à droite. Au premier palier, continuer à droite entre les vignes. En dessous, descendez en lisière d'un petit bois et franchissez un portillon métallique. Emprunter la D230 à droite sur 1 km.
        </description>
        <lieux>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">chemin Vignau</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115"> camin de Sobolle</lieu>
            <lieu type="batiment" coord="43.287530, -0.391115">ferme Sobolle</lieu>
            <lieu type="lieu_dit" coord="43.287530, -0.391115">Clos Lapeyre</lieu>
        </lieux>
    </etape>
    
    <etape numero ="5" libelle="Chemin de la Rec">
        <distance valeur="3060" unite="m"/>  
        <temps heure="00" minute="45"/> 
        <description>
            Au croisement de Roumiga, tourner à gauche, franchissez un pont et traversez la vallée vers le nord dans une cuvette profonde, agréable et paisible. Prenez à droite la D 217, puis aller à gauche vers St-Faust (2 km). Grimper le chemin de la Rec qui serpente en sous-bois et rejoignez la commune de St-Faust face à l'église (belle vue sur l'Ossau).
        </description>
        <lieux>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">croisement de Roumiga</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">chemin de la Rec</lieu>
            <lieu type="ville" coord="43.287530, -0.391115">commune de St-Faust</lieu>
        </lieux>
    </etape>
    
    <etape numero ="6" libelle="Les coteaux de St-Faust face.">
        <distance valeur="3915" unite="m"/>  
        <temps heure="01" minute="10"/> 
        <description>
            Emprunter la D 502 vers la droite pendant 1500 m et passer devant la Cité des Abeilles. Prenez le chemin Mantoulan à gauche et longer de belles vignes plantées sur un flanc sud. Suivez le balisage d'un chemin baptisé « les coteaux de St-Faust». Au sommet de la colline, prenez le beau chemin Constantine à droite qui file vers le nord. Il contourne deux exploitations (Larréheuga et Coutchous) et plonge entre les prairies. Rejoignez un chemin goudronné. En bas de la côte, virer à droite le long du ruisseau Lahourcade.
        </description>
        <lieux>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">D 502</lieu>
            <lieu type="batiment" coord="43.287530, -0.391115">Cité des Abeilles</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">chemin Mantoulan</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">les coteaux de St-Faust</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">chemin Constantine</lieu>
            <lieu type="voie_fluviale" coord="43.287530, -0.391115">ruisseau Lahourcade</lieu>
        </lieux>
    </etape>
    
    <etape numero ="7" libelle="Le ruisseau des Hies descente humide.">
        <distance valeur="3100" unite="m"/>  
        <temps heure="00" minute="45"/> 
        <description>
            Franchir le ruisseau à gué et tourner à droite (Panneau interdiction aux quads). S'élever rudement par un sentier dans les bois. Rejoignez l'église de St-Faust-de-bas, puis descendez à gauche par la D 502. Dans un virage prononcé à gauche, partir à droite à travers bois par le chemin Coureyou, puis rejoignez une nouvelle fois la D 502 qui conduit à l'entrée de Laroin. La quitter pour suivre le ruisseau des Hies en face. Franchir une passerelle et parvenez au centre du village. Traverser la D 2 et utiliser le chemin du Stade qui rejoint le ruisseau des Hies face à une passerelle. Longer le ruisseau puis passez sous la rocade D 2 par un tunnel à l'ambiance curieuse. 
        </description>
        <lieux>
            <lieu type="batiment" coord="43.287530, -0.391115">église de St-Faust-de-bas</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">D 502</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">chemin Coureyou</lieu>
            <lieu type="ville" coord="43.287530, -0.391115">Laroin</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">D 2</lieu>
            <lieu type="voie_routiere" coord="43.287530, -0.391115">chemin du Stade</lieu>
        </lieux>
    </etape>
    
    <etape numero ="8" libelle="Le gave de Pau">
        <distance valeur="4770" unite="m"/>  
        <temps heure="01" minute="15"/> 
        <description>
            Suivre la rive gauche du gave de Pau longuement où les amateurs d'oiseaux se régaleront en surprenant les hérons ou les cormorans. Laissez un centre équestre à gauche et ignorez juste après la remarquable passerelle piétons de Laroin aux haubans en fibre de verre. Rejoindre le pont de Billères où vous passerez dessous et l'emprunter pour franchir le gave. Prendre à droite à son extrémité est un sentier facile et continuer maintenant rive droite en longeant le golf de Billères par le sud. Contourner le restaurant "Au bord de l'eau" et franchissez la passerelle pour piétons afin de retrouver le parking de départ.
        </description>
        <lieux>
            <lieu type="voie_fluviale" coord="43.287530, -0.391115">gave de Pau</lieu>
            <lieu type="batiment" coord="43.287530, -0.391115">pont de Billères</lieu>
            <lieu type="batiment" coord="43.287530, -0.391115">golf de Billères</lieu>
            <lieu type="batiment" coord="43.287530, -0.391115">restaurant "Au bord de l'eau"</lieu>
        </lieux>
    </etape>
    
</randonnee>
