=== NephtysOrg/smcw/livrable3/bd__hierarchie.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Fichier bd__hierarchie.dtd -->
<!-- Besoin exprime : hierarchie du document -->
<!-- Auteur: Roland Bary -->

<!ELEMENT hierarchie (document)+>

<!ELEMENT document (section_preambule,section_description,section_thematique?,section_synthese) >
<!ATTLIST document id NMTOKEN #REQUIRED >
<!ELEMENT section_preambule (titre,intitule,paragraphe+) >
<!ELEMENT section_description (titre,sous_section+) >
<!ELEMENT section_thematique (thematique)+ >
<!ELEMENT thematique (titre,paragraphe+) >
<!ATTLIST thematique id NMTOKEN #REQUIRED
          type (culturelle) #REQUIRED > 
<!ELEMENT section_synthese (synthese)+ >
<!ELEMENT titre (#PCDATA) >
<!ELEMENT intitule (#PCDATA) >
<!ELEMENT paragraphe (#PCDATA) >
<!ELEMENT sous_section (sous_titre,paragraphe)+ >
    <!ATTLIST sous_section
        id NMTOKEN #REQUIRED
    >
<!ELEMENT synthese (sous_titre,liste)>
    <!ATTLIST synthese
        id NMTOKEN #REQUIRED
        type (technique | information) #REQUIRED
    >
<!ELEMENT sous_titre (#PCDATA) >
<!ELEMENT liste (item+) >
<!ELEMENT item (label,descriptif)>
    <!ATTLIST item
        id NMTOKEN #REQUIRED
    >
<!ELEMENT label (#PCDATA) >
<!ELEMENT descriptif (#PCDATA) >

=== NephtysOrg/smcw/livrable3/bd__hierarchie.xml
<?xml version='1.0' encoding='UTF-8' standalone="yes"?> 
<!DOCTYPE hierarchie SYSTEM "bd__hierarchie.dtd">
<!-- Fichier bd__hierarchie.xml -->
<!-- Besoin exprime : hierarchie du document -->
<!-- Auteur : Roland Bary -->

<hierarchie
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="bd__hierarchie.xsd" >
    <document id="1">
        <section_preambule>
            <titre>Pas de circuit</titre>
            <intitule>Les coteaux de Jurançon</intitule>
                <paragraphe>SITUATION : Région de Pau, coteaux de Jurançon</paragraphe>
                <paragraphe>"Une lumière blonde et dorée qui supprime les ombres" A. Derain. Le parcours se déroule en partie le long des rives du gave et offre la possibilité en hiver d'observer différentes espèces de canards, aigrettes, hérons et le délicat martin pêcheur. Mais c'est surtout la traversée d'une partie des vignobles de Jurançon avec son exceptionnel paysage sur les Pyrénées qui est au centre de cette randonnée. De Jurançon à Monein, couvrant une bande de 40 km de long pour 30 de large et sculptant des paysages extraordinaires, le vignoble de Jurançon a acquis depuis des lustres une réputation remarquable. Selon la coutume Henri IV fut baptisé avec du Jurançon et ses lèvres frottées d'une gousse d'ail. Depuis, il semble que le caractère des béarnais a épousé le goût ambré de ce vin légendaire avec la fougue de ce baptême historique. Cette balade au coeur de ce terroir magnifique respire le travail des hommes. Vignerons du soleil et des Pyrénées, ils ont su planter sur des pentes sévères ces rangs de vignes conduits en hautain souvent ponctués de rosiers flamboyants. Aux portes de Pau, ces paysages sont à la portée de beaucoup de randonneurs. L'automne et ses lumières dorées est une saison idéale pour parcourir ces parages aux couleurs de miel. Peut être, avec un peu de chance, pourrez-vous croquer quelques grappes échappées aux ciseaux du vigneron et oubliées du bec des grives.</paragraphe>
        </section_preambule>
        <section_description>
            <titre>DESCRIPTION</titre>
            <sous_section id="1">
                <sous_titre>1 - Avenue Joliot-Curie distance : 1220 m - temps : 00h15</sous_titre>
                <paragraphe>Il faut tourner le dos au gave de Pau et prendre la rue de l'Artisanat vers le sud. Traversez la double-voie et poursuivez en face par l'avenue Joliot-Curie. Laissez à droite le lycée professionnel de Jurançon tout en métal brillant et en tubes métalliques puis franchissez une passerelle pour pénétrer dans une zone de pavillons modernes. Poursuivez par la rue Auguste Renoir puis, au bout, virer à droite en direction de la rocade.</paragraphe> 
            </sous_section>
            <sous_section id="2">
                <sous_titre>2 - Le Clos Touzet distance : 2300 m - temps : 00h45</sous_titre>
                <paragraphe>Traverser la rocade puis continuez en vous élevant par le chemin de Monplaisir, à la limite d'un bois. Laisser les bâtiments du « Nid béarnais » à gauche et continuer en sous-bois. Débouchez au sommet du coteau face « Au Clos Touzet » où la vue sur la plaine de Pau mérite un long coup d'oeil. Poursuivez en face. Ne pas descendre trop longtemps vers Jurançon, mais suivre l'avenue des Frères Barthélemy en face.</paragraphe>          
            </sous_section>
            <sous_section id="3">
                <sous_titre>3 - Le chemin Mirabel distance : 1200 m - temps : 00h20</sous_titre>
                <paragraphe> Face à l'entrée du Clos Henri IV, au N° 223, descendre à droite le chemin Mirabel (panneau) qui se faufile en sous-bois. Juste avant l'entrée de la ferme Larrau (remarquer le séquoia isolé) prenez un chemin creux à gauche qui plonge dans un sous-bois magnifique. Il décrit une épingle et s'enfonce dans une forêt où la lumière pénètre difficilement. Rejoignez le lit d'un petit ruisseau que vous suivez vers l'aval. Mousses, lichens, fougères constituent le décor luxuriant de cette descente humide.</paragraphe>
            </sous_section>
            <sous_section id="4">
                <sous_titre>4 - Le Clos Lapeyre distance : 2430 m - temps : 00h45</sous_titre>
                <paragraphe>Emprunter la route à gauche (chemin Vignau) où vous rencontrez un chemin équestre (itinéraire équestre Pyrénéen) que vous suivrez maintenant facilement vers le sud. Franchissez un pont et grimpez une piste cimentée « camin de Sobolle ». Dépasser la belle ferme Sobolle et continuer dans le bois. Rejoignez un chemin goudronné et le suivre à gauche vers le Clos Lapeyre. Après la première vigne, descendre à droite. Au premier palier, continuer à droite entre les vignes. En dessous, descendez en lisière d'un petit bois et franchissez un portillon métallique. Emprunter la D230 à droite sur 1 km.</paragraphe>
            </sous_section>
            <sous_section id="5">
                <sous_titre>5 - Chemin de la Rec distance : 3060 m - temps : 00h45</sous_titre>
                <paragraphe>Au croisement de Roumiga, tourner à gauche, franchissez un pont et traversez la vallée vers le nord dans une cuvette profonde, agréable et paisible. Prenez à droite la D 217, puis aller à gauche vers St-Faust (2 km). Grimper le chemin de la Rec qui serpente en sous-bois et rejoignez la commune de St-Faust face à l'église (belle vue sur l'Ossau).</paragraphe>
            </sous_section>
            <sous_section id="6">
                <sous_titre>6 - Les coteaux de St-Faust distance : 3915 m - temps : 01h10</sous_titre>
                <paragraphe> Emprunter la D 502 vers la droite pendant 1500 m et passer devant la Cité des Abeilles. Prenez le chemin Mantoulan à gauche et longer de belles vignes plantées sur un flanc sud. Suivez le balisage d'un chemin baptisé « les coteaux de St-Faust». Au sommet de la colline, prenez le beau chemin Constantine à droite qui file vers le nord. Il contourne deux exploitations (Larréheuga et Coutchous) et plonge entre les prairies. Rejoignez un chemin goudronné. En bas de la côte, virer à droite le long du ruisseau Lahourcade.
                </paragraphe>
            </sous_section>
            <sous_section id="7">
                <sous_titre>7 - Le ruisseau des Hies distance : 3100 m - temps : 00h45
                </sous_titre>
                <paragraphe>Franchir le ruisseau à gué et tourner à droite (Panneau interdiction aux quads). S'élever rudement par un sentier dans les bois. Rejoignez l'église de St-Faust-de-bas, puis descendez à gauche par la D 502. Dans un virage prononcé à gauche, partir à droite à travers bois par le chemin Coureyou, puis rejoignez une nouvelle fois la D 502 qui conduit à l'entrée de Laroin. La quitter pour suivre le ruisseau des Hies en face. Franchir une passerelle et parvenez au centre du village. Traverser la D 2 et utiliser le chemin du Stade qui rejoint le ruisseau des Hies face à une passerelle. Longer le ruisseau puis passez sous la rocade D 2 par un tunnel à l'ambiance curieuse.</paragraphe>
            </sous_section>
            <sous_section id="8">
                <sous_titre>8 - Le gave de Pau distance : 4770 m - temps : 01h15</sous_titre>
                <paragraphe>Suivre la rive gauche du gave de Pau longuement où les amateurs d'oiseaux se régaleront en surprenant les hérons ou les cormorans. Laissez un centre équestre à gauche et ignorez juste après la remarquable passerelle piétons de Laroin aux haubans en fibre de verre. Rejoindre le pont de Billères où vous passerez dessous et l'emprunter pour franchir le gave. Prendre à droite à son extrémité est un sentier facile et continuer maintenant rive droite en longeant le golf de Billères par le sud. Contourner le restaurant "Au bord de l'eau" et franchissez la passerelle pour piétons afin de retrouver le parking de départ.</paragraphe>
            </sous_section>          
        </section_description>
        
        <section_thematique>
            <thematique id="1" type="culturelle">
                <titre>THEMATIQUE CULTURELLE</titre>
                <paragraphe>La richesse des paysages de ces coteaux de Jurançon est directement liée au travail de l'homme. Sur ces monts béarnais se pratique la polyculture. Variés, parsemés de petites parcelles où se côtoient la vigne, le haricot tarbais et l'élevage de blondes d'Aquitaine, ce damier de paysage agricole s'oppose à la monoculture intensive des plaines à maïs voisines de Pau et de Mourenx. En agriculture, la polyculture est le fait de cultiver plusieurs espèces de plantes dans une même exploitation agricole ou plus largement dans une région naturelle. Ici, le maïs est semé au fond du vallon et profite de l'humidité des brouillards matinaux. A mi-pente, autour des granges croit le foin qui servira à l'alimentation des bestiaux. Enfin, sur les crêtes bénéficiant de toutes les expositions, face au soleil se développent les vignes de Jurançon. C'est l'expression la plus simple et la plus aboutit du monde agricole où la main de l'homme compose directement le paysage et influe profitablement sur son environnement.</paragraphe>
            </thematique>
        </section_thematique>
        <section_synthese>
           <synthese id="1" type="technique">
               <sous_titre>FICHE TECHNIQUE</sous_titre> 
               <liste>
                   <item id="1">
                       <label>INFORMATION :</label>
                       <descriptif>Office de Tourisme de Pau, tél: 05 59 27 27 08 Météorologie : 08 36 68 02 (64)</descriptif>
                   </item>
                   <item id="2">
                       <label>RECOMMANDATIONS :</label>
                       <descriptif>L'itinéraire emprunte des petits bouts de randonnées abondamment balisés et facilement repérables. Evitez de le parcourir après un fort orage, quelques raides chemins en terre peuvent être boueux et le gué de Lahourcade peut alors demander un détour.</descriptif>
                   </item>
