=== NephtysOrg/smcw/livrable3/fil_eau__fiches.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auteur: Roland Bary -->

<!ELEMENT fiches (fiche_technique|fiche_information)*>
    <!-- une fiche doit impÃ©rativement contenir les balises entre ()-->
    <!ELEMENT fiche_technique (information|recommandations|difficulte|epoque|denivele|longueur|alt_dep|alt_arr|alt_max|horaire|lieu_dep|lieu_arr|commune_dep|commune_arr)*>
        <!ELEMENT information (#PCDATA)>
        <!ELEMENT recommandations (#PCDATA)>
        <!ELEMENT difficulte (#PCDATA)>
        <!ELEMENT epoque (saison*)>
        	<!ELEMENT saison (#PCDATA)>
        <!ELEMENT valeur (#PCDATA)>
        <!ELEMENT unite (#PCDATA)>
        <!ELEMENT denivele (valeur|unite)*>
        <!ELEMENT longueur (valeur|unite)* >
        <!ELEMENT alt_dep (valeur|unite)* >
        <!ELEMENT alt_arr (valeur|unite)* >
        <!ELEMENT alt_max (valeur|unite)* >
        <!ELEMENT horaire (heure|minute|seconde)*>
                <!ELEMENT heure (#PCDATA)>
                <!ELEMENT minute (#PCDATA)>
                <!ELEMENT seconde (#PCDATA)>
        <!ELEMENT lieu_dep (#PCDATA)>
        <!ELEMENT lieu_arr (#PCDATA)>
        <!ELEMENT commune_dep (#PCDATA)>
        <!ELEMENT commune_arr (#PCDATA)>
    <!ELEMENT fiche_information (cartes|carroyage|nom|acces|parkings|type_parcours|types_chemin|types_terrain|liste_materiel)*>
        <!ELEMENT cartes (carte+)>
        	<!ELEMENT carte (#PCDATA)>
        <!ELEMENT carroyage (#PCDATA)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT acces (#PCDATA)>
        <!ELEMENT parkings (parking+)>
        	<!ELEMENT parking (#PCDATA)>
        <!ELEMENT type_parcours (#PCDATA)>
        <!ELEMENT types_chemin (type_chemin+)>
        	<!ELEMENT type_chemin (#PCDATA)>
        <!ELEMENT types_terrain (type_terrain+)>
        	<!ELEMENT type_terrain (#PCDATA)>
        <!ELEMENT liste_materiel (materiel+)>
        	<!ELEMENT materiel (#PCDATA)>

=== NephtysOrg/smcw/livrable2/fil_eau__fiches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auteur: Roland Bary -->

<!DOCTYPE fiches SYSTEM "fil_eau__fiches.dtd">

<fiches>
    <fiche_technique>
        <information>Office de Tourisme de Pau, tél: 05 59 27 27 08 Météorologie: 08 36 68 02 (64)</information>  
        <recommandations>L'itinéraire emprunte des petits bouts de randonnées abondamment balisés et facilement repérables. Evitez de le parcourir après un fort orage, quelques raides chemins en terre peuvent être boueux et le gué de Lahourcade peut alors demander un détour.</recommandations>
        <difficulte>RANDO FACILE</difficulte>
        <epoque><saison>HIVER</saison> <saison>PRINTEMPS</saison><saison>AUTOMNE</saison></epoque>
        <denivele><valeur>422</valeur><unite>m</unite></denivele>
        <longueur><valeur>21995</valeur><unite>m</unite></longueur>
        <alt_dep><valeur>170</valeur><unite>m</unite></alt_dep>
        <alt_arr><valeur>170</valeur><unite>m</unite></alt_arr>
        <alt_max><valeur>328</valeur><unite>m</unite></alt_max>
        <horaire><heure>06</heure><minute>00</minute><seconde>00</seconde></horaire>
        <lieu_dep>Stade de Jurançon</lieu_dep>
        <lieu_arr>Stade de Jurançon</lieu_arr>
        <commune_dep>Jurançon</commune_dep>
        <commune_arr>Jurançon</commune_arr>
    </fiche_technique>
    
    <fiche_information>
        <cartes><carte>PAU</carte></cartes>
        <carroyage>1545ET</carroyage> 
        <nom>IGN TOP25</nom> 
        <acces>De Pau (sortie n°10 de l'A64) prenez la direction Saragosse-Jurançon jusqu'au pont d'Espagne que vous franchissez vers le sud. Prenez à droite la rocade (Av du Corps-Franc Pommies) toujours en direction Saragosse et dépassez un premier rond point. Parcourez 350 m et prenez à droite la rue de l'Artisanat jusqu'à un petit parking situé rive gauche du gave de Pau.</acces>
        <parkings><parking>Rive gauche du gave près d'une passerelle pour piétons et d'un parcours d'entraînement pour les chiens de défense. C'est aussi le départ d'un circuit de footing.</parking></parkings>
        <type_parcours>BOUCLE</type_parcours> 
        <types_chemin><type_chemin>CHEMIN GOUDRONNE</type_chemin><type_chemin>SENTIER BALISE</type_chemin></types_chemin>
        <types_terrain><type_terrain>ZONE AGRICOLE</type_terrain><type_terrain>ZONE URBAINE</type_terrain></types_terrain>
        <liste_materiel><materiel>Jumelles</materiel><materiel>chaussures de marche</materiel><materiel>bâtons</materiel></liste_materiel>
    </fiche_information>
</fiches>
