=== NephtysOrg/smcw/livrable4/bd__fiches.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:include schemaLocation="librairie.xsd"/>
  
  <xs:element name="fiches">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fiche_technique"/>
        <xs:element ref="fiche_information"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="fiche_technique">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="information"/>
        <xs:element ref="recommandations"/>
        <xs:element ref="difficulte"/>
        <xs:element ref="epoque"/>
        <xs:element ref="taille"/>
        <xs:element ref="altitude"/>
        <xs:element ref="horaire"/>
        <xs:element ref="depart"/>
        <xs:element ref="arrivee"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="information" type="xs:string"/>
  
  
  <xs:element name="recommandations" type="xs:string"/>
  
  
  <xs:element name="difficulte" type="difficulte"/>
   
  
  
  <xs:element name="epoque">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="4" ref="saison"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="saison" type="saison"/>
  
  
  <xs:element name="taille">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.taille"/>
    </xs:complexType>
  </xs:element>
  
  <xs:attributeGroup name="attlist.taille">
    
    <xs:attribute name="denivele" use="required" type="xs:positiveInteger" />
    
    <xs:attribute name="longueur" use="required" type="xs:positiveInteger" />
    
    <xs:attribute name="unite" use="required" type="uniteDistance"/>
  </xs:attributeGroup>
  
  <xs:element name="altitude">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.altitude"/>
    </xs:complexType>
  </xs:element>
  
  <xs:attributeGroup name="attlist.altitude">
    
    <xs:attribute name="depart" use="required" type="xs:positiveInteger" />
    
    <xs:attribute name="arrive" use="required" type="xs:positiveInteger" />
    
    <xs:attribute name="maximale" use="required" type="xs:positiveInteger" />
    
    <xs:attribute name="unite" use="required" type="uniteDistance"/>
  </xs:attributeGroup>
  
  
  <xs:element name="horaire">
    <xs:complexType>
      <xs:attribute name="valeur" type="xs:time"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="depart">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.depart"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.depart">
    
    <xs:attribute name="lieu" use="required" type="xs:string" />
    
    <xs:attribute name="commune" use="required" type="xs:string" />
  </xs:attributeGroup>
  
  <xs:element name="arrivee">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.arrivee"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.arrivee">
    
    <xs:attribute name="lieu" use="required" type="xs:string" />
    
    <xs:attribute name="commune" use="required" type="xs:string" />
  </xs:attributeGroup>
  
  <xs:element name="fiche_information">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cartes"/>
        <xs:element ref="carroyage"/>
        <xs:element ref="nom"/>
        <xs:element ref="acces"/>
        <xs:element ref="parkings"/>
        <xs:element ref="type_parcours"/>
        <xs:element ref="types_chemin"/>
        <xs:element ref="types_terrain"/>
        <xs:element ref="liste_materiel"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="cartes">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="carte"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="carte" type="xs:string"/>
  
  <xs:element name="carroyage">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{0,4}[A-Z]{2}" />
    </xs:restriction>
  </xs:simpleType>
  </xs:element>
  
  <xs:element name="nom" type="xs:string"/>
  
  <xs:element name="acces" type="xs:string"/>
  
  
  <xs:element name="parkings">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="parking"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="parking" type="xs:string"/>
  
  
  <xs:element name="type_parcours">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="BOUCLE"/>
        <xs:enumeration value="TRAVERSEE"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  
  <xs:element name="types_chemin">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="type_chemin"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="type_chemin">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="CHEMIN GOUDRONNE"/>
        <xs:enumeration value="SENTIER BALISE"/>
        <xs:enumeration value="CHEMIN DE TERRE"/>
        <xs:enumeration value="SENTIER CAIRNE"/>
        <xs:enumeration value="HORS SENTIER"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="types_terrain">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="type_terrain"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="type_terrain">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="ZONE AGRICOLE" />
        <xs:enumeration value="EBOULIS" />
        <xs:enumeration value="PENTE D HERBE" />
        <xs:enumeration value="ZONE URBAINE" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="liste_materiel">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="materiel"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="materiel" type="xs:string"/>
</xs:schema>

=== NephtysOrg/smcw/livrable4/bd__fiches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auteur : Charles Follet -->

<fiches 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="bd__fiches.xsd"
    xmlns="namespace:rbary.univ-pau.fr:f"
    >
    <fiche_technique>
        <information>Office de Tourisme de Pau, tél: 05 59 27 27 08 Météorologie: 08 36 68 02 (64)</information>  
        <recommandations>L'itinéraire emprunte des petits bouts de randonnées abondamment balisés et facilement repérables. Evitez de le parcourir après un fort orage, quelques raides chemins en terre peuvent être boueux et le gué de Lahourcade peut alors demander un détour.</recommandations>
        <difficulte>FACILE</difficulte>
        <epoque><saison>HIVER</saison> <saison>PRINTEMPS</saison><saison>AUTOMNE</saison></epoque>
        <taille denivele="422" longueur="21995" unite="m"/>
        <altitude depart="170" arrive="170" maximale="328" unite="m"/>
        <horaire valeur="06:00:00"/>
        <depart lieu="Stade de Jurançon" commune="Jurançon"/>
        <arrivee lieu="Stade de Jurançon" commune="Jurançon"/>
    </fiche_technique>
    
    <fiche_information>
        <cartes><carte>PAU</carte></cartes>
        <carroyage>1545ET</carroyage> 
        <nom>IGN TOP25</nom> 
        <acces>De Pau (sortie n°10 de l'A64) prenez la direction Saragosse-Jurançon jusqu'au pont d'Espagne que vous franchissez vers le sud. Prenez à droite la rocade (Av du Corps-Franc Pommies) toujours en direction Saragosse et dépassez un premier rond point. Parcourez 350 m et prenez à droite la rue de l'Artisanat jusqu'à un petit parking situé rive gauche du gave de Pau.</acces>
        <parkings><parking>Rive gauche du gave près d'une passerelle pour piétons et d'un parcours d'entraînement pour les chiens de défense. C'est aussi le départ d'un circuit de footing.</parking></parkings>
        <type_parcours>BOUCLE</type_parcours> 
        <types_chemin><type_chemin>CHEMIN GOUDRONNE</type_chemin><type_chemin>SENTIER BALISE</type_chemin></types_chemin>
        <types_terrain><type_terrain>ZONE AGRICOLE</type_terrain><type_terrain>ZONE URBAINE</type_terrain></types_terrain>
        <liste_materiel><materiel>Jumelles</materiel><materiel>chaussures de marche</materiel><materiel>bâtons</materiel></liste_materiel>
    </fiche_information>
</fiches>
