=== NephtysOrg/smcw/livrable2/bd__fiches.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auteur : Charles Follet -->

	<!ELEMENT fiches (fiche_technique,fiche_information)>
	    <!-- une fiche doit impÃ©rativement contenir les balises entre ()-->
	    <!ELEMENT fiche_technique (information,recommandations,difficulte,epoque,taille,altitude,horaire,depart, arrivee)>
		<!ELEMENT information (#PCDATA)>
		<!ELEMENT recommandations (#PCDATA)>
		<!ELEMENT difficulte (#PCDATA)>
		<!ELEMENT epoque (saison*)>	
			<!ELEMENT saison (#PCDATA)>
		<!ELEMENT taille EMPTY>
			<!ATTLIST taille
				denivele CDATA #REQUIRED
				longueur CDATA #REQUIRED
				unite (m|km) #REQUIRED
			>
		<!ELEMENT altitude EMPTY>
			<!ATTLIST altitude
				depart CDATA #REQUIRED
				arrive CDATA #REQUIRED
				maximale CDATA #REQUIRED
				unite (m|km) #REQUIRED
			>
		<!ELEMENT horaire EMPTY>
			<!ATTLIST horaire
				heure CDATA #REQUIRED
				minute CDATA #REQUIRED
				seconde CDATA #REQUIRED
			>
			
		<!ELEMENT depart EMPTY>
			<!ATTLIST depart
				lieu CDATA #REQUIRED
				commune CDATA #REQUIRED
			>
		<!ELEMENT arrivee EMPTY>
			<!ATTLIST arrivee
				lieu CDATA #REQUIRED
				commune CDATA #REQUIRED
			>
	    <!ELEMENT fiche_information (cartes,carroyage,nom,acces,parkings,type_parcours,types_chemin,types_terrain,liste_materiel)>
		<!ELEMENT cartes (carte+)>
			<!ELEMENT carte (#PCDATA)>
		<!ELEMENT carroyage (#PCDATA)>
		<!ELEMENT nom (#PCDATA)>
		<!ELEMENT acces (#PCDATA)>
		<!ELEMENT parkings (parking+)>
			<!ELEMENT parking (#PCDATA)>
		<!ELEMENT type_parcours (#PCDATA)>
		<!ELEMENT types_chemin (type_chemin+)>
			<!ELEMENT type_chemin (#PCDATA)>
		<!ELEMENT types_terrain (type_terrain+)>
			<!ELEMENT type_terrain (#PCDATA)>
		<!ELEMENT liste_materiel (materiel+)>
			<!ELEMENT materiel (#PCDATA)>

=== NephtysOrg/smcw/livrable3/bd__fiches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auteur : Charles Follet -->

<!DOCTYPE fiches SYSTEM "bd__fiches.dtd">

<fiches>
    <fiche_technique>
        <information>Office de Tourisme de Pau, tél: 05 59 27 27 08 Météorologie: 08 36 68 02 (64)</information>  
        <recommandations>L'itinéraire emprunte des petits bouts de randonnées abondamment balisés et facilement repérables. Evitez de le parcourir après un fort orage, quelques raides chemins en terre peuvent être boueux et le gué de Lahourcade peut alors demander un détour.</recommandations>
        <difficulte>FACILE</difficulte>
        <epoque><saison>HIVER</saison> <saison>PRINTEMPS</saison><saison>AUTOMNE</saison></epoque>
        <taille denivele="422" longueur="21995" unite="m"/>
        <altitude depart="170" arrive="170" maximale="328" unite="m"/>
        <horaire heure="06" minute="00" seconde="00"/>
        <depart lieu="Stade de Jurançon" commune="Jurançon"/>
        <arrivee lieu="Stade de Jurançon" commune="Jurançon"/>
    </fiche_technique>
    
    <fiche_information>
        <cartes><carte>PAU</carte></cartes>
        <carroyage>1545ET</carroyage> 
        <nom>IGN TOP25</nom> 
        <acces>De Pau (sortie n°10 de l'A64) prenez la direction Saragosse-Jurançon jusqu'au pont d'Espagne que vous franchissez vers le sud. Prenez à droite la rocade (Av du Corps-Franc Pommies) toujours en direction Saragosse et dépassez un premier rond point. Parcourez 350 m et prenez à droite la rue de l'Artisanat jusqu'à un petit parking situé rive gauche du gave de Pau.</acces>
        <parkings><parking>Rive gauche du gave près d'une passerelle pour piétons et d'un parcours d'entraînement pour les chiens de défense. C'est aussi le départ d'un circuit de footing.</parking></parkings>
        <type_parcours>BOUCLE</type_parcours> 
        <types_chemin><type_chemin>CHEMIN GOUDRONNE</type_chemin><type_chemin>SENTIER BALISE</type_chemin></types_chemin>
        <types_terrain><type_terrain>ZONE AGRICOLE</type_terrain><type_terrain>ZONE URBAINE</type_terrain></types_terrain>
        <liste_materiel><materiel>Jumelles</materiel><materiel>chaussures de marche</materiel><materiel>bâtons</materiel></liste_materiel>
    </fiche_information>
</fiches>
